# Generated by Django 4.1.7 on 2023-04-11 20:15

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_servicepage_body_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('title', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(help_text='Text to display', required=True))])), ('cards', wagtail.blocks.StructBlock([('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Title text for card, max length 100 chars', max_length=100)), ('text', wagtail.blocks.TextBlock(help_text='Optional text for card, max length 255 chars', max_length=255, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image will automatically be cropped to 570x370'))])))]))], blank=True, null=True, use_json_field=None),
        ),
    ]
